####################################################
# IBM AltoroJ
# (c) Copyright IBM Corp. 2008, 2015 All Rights Reserved.
####################################################

# This is an AltoroJ 3.0+ application properties file
# Place it in AltoroJ's WEB-INF folder
# In this file comments are represented by # or // at the start of each line
# Enable those properties you would like to enable by uncommenting them


#################### BEHAVIOR SETTINGS ########################

#### enableAdminFunctions property enables administrative functions in AltoroJ (adding users, changing passwords, etc)

#enableAdminFunctions=true


#### specialLink property changes certain links in AltoroJ (e.g. "Search News Articles" in the authenticated user navigation panel)
#### to the link specified in this property

#specialLink=http://www.warez.com


#### advancedStaticPageProcessing property enables advanced file/page lookup using Bash or Command Prompt

#advancedStaticPageProcessing=true


#### enableFeedbackRetention property turns on AltoroJ functionality to store feedback information in its database

#enableFeedbackRetention=true



#################### DATABASE SETTINGS ########################

#### database.alternateDataSource property allows AltoroJ to connect to an external database (e.g. DB2)
#### This property is the name of the data source configured in tomcat's context.xml which contains details for this database connection
#### This will also require adding in the appropriate JDBC driver JAR.
#### See the following URL for more details: https://tomcat.apache.org/tomcat-7.0-doc/jndi-datasource-examples-howto.html
#### IMPORTANT: If you use this property, you must also set database.reinitializeOnStart to true the first time you run AltoroJ
#### and log into the application. This is required to initialize AltoroJ data. You can disable database.reinitializeOnStart afterwards.
#### Failure to use database.reinitializeOnStart=true at least once will cause AltorJ to fail unless you manually create DB contents

#database.alternateDataSource=jdbc/AltoroDB


#### database.reinitializeOnStart setting forces AltoroJ to reinitialize its database every time Tomcat is restarted
#### instead of only initializing it if AltoroJ database does not exist. You MUST use this setting at least once if using an external DB.

#database.reinitializeOnStart=true
